### Scenario: "The Bookshop Analyst"

You're a data analyst for an online bookshop. The operations team has exported their inventory to a CSV and they need your help making sense of it

## Part 1: Conceptual Check (15 min)

**Question 1:** What is the key difference between a Pandas `Series` and a `DataFrame`?

**Answer:** Series is 1 dimensional, dataframe is 2 dimensional

---

**Question 2:** You run `df.loc[0:3]`. How many rows do you get? What about `df.iloc[0:3]`?

**Answer:** df.loc[0:3] gives you 4 rows because its asking for labels 0, 1, 2 and 3. Df.iloc[0:3] gives you 3 rows because it works like indexing, so it gives you 0, 1 and 2 (stops before 3)

---

**Question 3:** You have a DataFrame with a `price` column stored as `object` type (strings like "£45.99"). What problem does this cause, and how do you fix it?

**Answer:** You can't do mathematical operations on a string column, you would need to convert it to float using .astype()"

---

**Question 4:** When would you use `.apply()` instead of a direct vectorised operation like `df['col'] * 2`?

**Answer:** When you have a complex function that you want to execute like labelling cells when they are a certain value

---

**Question 5:** How do you select all numeric columns from a DataFrame, excluding float types?

**Answer:** df.select\_dtypes(include = 'number', exclude = 'float')

## Part 2: Practical Challenge (30–45 min)

### Challenge 1: Build and Inspect the Dataset

Create the following DataFrame and perform a health check:

In [3]:
import pandas as pd

books = pd.DataFrame({
    'title': ['The Pragmatic Programmer', 'Clean Code', 'Python Crash Course',
              'Data Science from Scratch', 'Designing Data-Intensive Apps'],
    'author': ['Hunt & Thomas', 'Robert Martin', 'Eric Matthes',
               'Joel Grus', 'Martin Kleppmann'],
    'genre': ['Tech', 'Tech', 'Tech', 'Data', 'Data'],
    'price': [45.99, 38.50, 29.99, 42.00, 55.00],
    'units_sold': [120, 95, 200, 80, 60],
    'in_stock': [True, True, False, True, False]
})

In [10]:
#1. Use `.info()` — how many non-null values does each column have?
print("Books info")
books.info()
#2. Use `.describe()` — what's the average price and maximum units sold?
print("Books describe")
books.describe()
#3. Add a `revenue` column: `price × units_sold`.
books['revenue'] = books.price * books.units_sold
display(books)
#4. What is the total revenue across all books?
print("Total Revenue",books['revenue'].sum())

Books info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   title       5 non-null      object
 1   author      5 non-null      object
 2   genre       5 non-null      object
 3   price       5 non-null      float64
 4   units_sold  5 non-null      int64
 5   in_stock    5 non-null      bool
 6   revenue     5 non-null      float64
dtypes: bool(1), float64(2), int64(1), object(3)
memory usage: 373.0+ bytes
Books describe

,title,author,genre,price,units_sold,in_stock,revenue
0,The Pragmatic Programmer,Hunt & Thomas,Tech,45.99,120,True,5518.8
1,Clean Code,Robert Martin,Tech,38.50,95,True,3657.5
2,Python Crash Course,Eric Matthes,Tech,29.99,200,False,5998.0
3,Data Science from Scratch,Joel Grus,Data,42.00,80,True,3360.0
4,Designing Data-Intensive Apps,Martin Kleppmann,Data,55.00,60,False,3300.0

Total Revenue 21834.3

### Challenge 2: Indexing & Filtering

In [ ]:
#**Tasks:**
#1. Use `.loc` to select only `title` and `revenue` for Data genre books.
print("Title and revenue for data genre books")
display(books.loc[books['genre'] == 'Data',['title','revenue']])

#2. Use `.iloc` to retrieve the last 3 rows and first 3 columns.
print("Last 3 rows, 1st 3 columns")
display(books.iloc[-3:,:3])


#3. Filter books that are **in stock** AND have a **price above £40**.
#mask_stock = (books['price'] > 40)
#mask_price = (books['in_stock'] == True)
#combined_mask = mask_stock & mask_price
#display(books[combined_mask])
print("In stock + price > 40")
display(books[(books['in_stock'] == True) & (books['price'] > 40)])

#4. Find the book with the **highest revenue** using `.loc` with `.idxmax()`
idxmax = books['revenue'].idxmax()
print("Max ID")
display(books.iloc[[books['revenue'].idxmax()]])

Title and revenue

                           title  revenue
3      Data Science from Scratch   3360.0
4  Designing Data-Intensive Apps   3300.0

Last 3 rows, 1st 3 columns

                           title            author genre
2            Python Crash Course      Eric Matthes  Tech
3      Data Science from Scratch         Joel Grus  Data
4  Designing Data-Intensive Apps  Martin Kleppmann  Data

In stock + price > 40

,title,author,genre,price,units_sold,in_stock,revenue,price_tier,sales_rank,genre_code
0,The Pragmatic Programmer,Hunt & Thomas,Tech,45.99,120,True,5518.8,Standard,2.0,0
3,Data Science from Scratch,Joel Grus,Data,42.00,80,True,3360.0,Standard,4.0,1

Max ID

,title,author,genre,price,units_sold,in_stock,revenue,price_tier,sales_rank,genre_code
2,Python Crash Course,Eric Matthes,Tech,29.99,200,False,5998.0,Budget,1.0,0

### Challenge 3: Transform, Sort & Rank

In [46]:
#1. Use `.apply()` to add a `price_tier` column: `'Budget'` (< £35), `'Standard'` (£35–£50), `'Premium'` (> £50).

def price_tier(x):
    if x < 35: 
        return "Budget"
    elif x <50:
        return "Standard" 
    else: 
        return "Premium"

books['price_tier'] = books['price'].apply(price_tier)
print("Price tier")
display(books)

#2. Sort the DataFrame by `revenue` descending.
print("Sort revenue descending")
display(books.sort_values(by='revenue',ascending=False))

#3. Add a `sales_rank` column using `.rank(ascending=False)`.
print("Sales rank")
books['sales_rank'] = books['revenue'].rank(ascending=False)
display(books.sort_values(by='revenue',ascending=False))

#4. Use `.map()` to encode `genre` as a number: `{'Tech': 0, 'Data': 1}`.
books['genre_code'] = books['genre'].map({'Tech':0,'Data':1})

print("Genre_code")
display(books.sort_values(by='revenue',ascending=False))

Price tier

,title,author,genre,price,units_sold,in_stock,revenue,price_tier,sales_rank,genre_code
0,The Pragmatic Programmer,Hunt & Thomas,Tech,45.99,120,True,5518.8,Standard,2.0,0
1,Clean Code,Robert Martin,Tech,38.50,95,True,3657.5,Standard,3.0,0
2,Python Crash Course,Eric Matthes,Tech,29.99,200,False,5998.0,Budget,1.0,0
3,Data Science from Scratch,Joel Grus,Data,42.00,80,True,3360.0,Standard,4.0,1
4,Designing Data-Intensive Apps,Martin Kleppmann,Data,55.00,60,False,3300.0,Premium,5.0,1

Sort revenue descending

,title,author,genre,price,units_sold,in_stock,revenue,price_tier,sales_rank,genre_code
2,Python Crash Course,Eric Matthes,Tech,29.99,200,False,5998.0,Budget,1.0,0
0,The Pragmatic Programmer,Hunt & Thomas,Tech,45.99,120,True,5518.8,Standard,2.0,0
1,Clean Code,Robert Martin,Tech,38.50,95,True,3657.5,Standard,3.0,0
3,Data Science from Scratch,Joel Grus,Data,42.00,80,True,3360.0,Standard,4.0,1
4,Designing Data-Intensive Apps,Martin Kleppmann,Data,55.00,60,False,3300.0,Premium,5.0,1

Sales rank

,title,author,genre,price,units_sold,in_stock,revenue,price_tier,sales_rank,genre_code
2,Python Crash Course,Eric Matthes,Tech,29.99,200,False,5998.0,Budget,1.0,0
0,The Pragmatic Programmer,Hunt & Thomas,Tech,45.99,120,True,5518.8,Standard,2.0,0
1,Clean Code,Robert Martin,Tech,38.50,95,True,3657.5,Standard,3.0,0
3,Data Science from Scratch,Joel Grus,Data,42.00,80,True,3360.0,Standard,4.0,1
4,Designing Data-Intensive Apps,Martin Kleppmann,Data,55.00,60,False,3300.0,Premium,5.0,1

Genre_code

,title,author,genre,price,units_sold,in_stock,revenue,price_tier,sales_rank,genre_code
2,Python Crash Course,Eric Matthes,Tech,29.99,200,False,5998.0,Budget,1.0,0
0,The Pragmatic Programmer,Hunt & Thomas,Tech,45.99,120,True,5518.8,Standard,2.0,0
1,Clean Code,Robert Martin,Tech,38.50,95,True,3657.5,Standard,3.0,0
3,Data Science from Scratch,Joel Grus,Data,42.00,80,True,3360.0,Standard,4.0,1
4,Designing Data-Intensive Apps,Martin Kleppmann,Data,55.00,60,False,3300.0,Premium,5.0,1